controller_manager:
  ros__parameters:
    update_rate: 10 # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mowbot_velocity_controller:
      type: diff_drive_controller/DiffDriveController

mowbot_velocity_controller:
  ros__parameters:    
    left_wheel_names: ["left_track_front_wheel_joint", "left_track_rear_wheel_joint", "left_track_middle_wheel_joint"]
    right_wheel_names: ["right_track_front_wheel_joint", "right_track_rear_wheel_joint", "right_track_middle_wheel_joint"]

    wheel_separation: 1.16
    wheel_radius: 0.15

    odom_frame_id: odom
    base_frame_id: base_link

    open_loop: false
    enable_odom_tf: false

    cmd_vel_timeout: 0.5
    use_stamped_vel: false

    preserve_turning_radius: true

    publish_cmd: true

    publish_wheel_data: true

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    # linear.x.has_velocity_limits: true
    # linear.x.has_acceleration_limits: true
    # linear.x.has_jerk_limits: false
    # linear.x.max_velocity: 1.0
    # linear.x.min_velocity: -1.0
    # linear.x.max_acceleration: 1.0
    # linear.x.max_jerk: 0.0
    # linear.x.min_jerk: 0.0

    # angular.z.has_velocity_limits: true
    # angular.z.has_acceleration_limits: true
    # angular.z.has_jerk_limits: false
    # angular.z.max_velocity: 1.0
    # angular.z.min_velocity: -1.0
    # angular.z.max_acceleration: 1.0
    # angular.z.min_acceleration: -1.0
    # angular.z.max_jerk: 0.0
    # angular.z.min_jerk: 0.0