<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="mowbot">

  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="length" value="1.34"/>
  <xacro:property name="width" value="1.26"/>
  <xacro:property name="height" value="0.662"/>

  <material name="red">
    <color rgba="0.8 0.0 0.0 1.0"/>
  </material>

  <material name="grey">
    <color rgba="0.5 0.5 0.5 1.0"/>
  </material>

  <material name="orange">
    <color rgba="1.0 0.4235 0.0392 1.0"/>
  </material>

  <link name="base_footprint">
    <visual>
      <geometry>
        <mesh filename="package://mowbot_description/meshes/mowbot_v01.stl" scale="1.0 1.0 1.0"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <collision>
      <geometry>
        <box size="${length} ${width} ${height}"/>
      </geometry>
    </collision>
  </link>

  <link name="base_link">
  </link>

  <joint name="footprint_to_base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0.0 0.0 0.335" rpy="0.0 0.0 0.0"/>
  </joint>

  <link name="imu_link">
    <visual>
      <geometry>
        <box size="0.02 0.025 0.01"/>
      </geometry>
      <material name="red"/>
    </visual>
  </link>

  <joint name="base_to_imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="-0.14 0.0 ${height - 0.335 + 0.015}" rpy="0.0 0.0 0.0"/>
    <!-- <origin xyz="-0.14 0.0 ${height - 0.335 + 0.015}" rpy="0.0 0.0 ${PI}"/> -->
  </joint>

  <link name="mag_link"></link>

  <joint name="imu_to_mag_joint" type="fixed">
    <parent link="imu_link"/>
    <child link="mag_link"/>
    <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
  </joint>


  <link name="laser_link">
    <visual>
      <geometry>
        <cylinder radius="0.035" length="0.04"/>
      </geometry>
      <material name="grey"/>
    </visual>
  </link>

  <joint name="base_to_laser_joint" type="fixed">
    <parent link="base_link"/>
    <child link="laser_link"/>
    <origin xyz="0.2 0.0 ${height - 0.335 + 0.2}" rpy="0.0 0.0 ${PI}"/>
  </joint>

  <link name="camera_link">
    <visual>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
      <material name="grey"/>
    </visual>
  </link>

  <joint name="base_to_camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="0.55 0.0 ${height - 0.335 + 0.08}" rpy="0.0 0.0 0.0"/>
  </joint>

  <link name="uwb_tag_link">
  </link>

  <joint name="uwb_tag_joint" type="fixed">
    <parent link="base_link"/>
    <child link="uwb_tag_link"/>
    <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
  </joint>

  <link name="gps_right_link">
  </link>

  <joint name="base_to_gps_right_joint" type="fixed">
    <parent link="base_link"/>
    <child link="gps_right_link"/>
    <origin xyz="-0.1 -0.52 ${height - 0.335 -0.05}" rpy="0.0 0.0 0.0"/>
  </joint>

  <link name="gps_left_link">
  </link>

  <joint name="base_to_gps_left_joint" type="fixed">
    <parent link="base_link"/>
    <child link="gps_left_link"/>
    <origin xyz="-0.1 0.52 ${height - 0.335 - 0.05}" rpy="0.0 0.0 0.0"/>
  </joint>

</robot>