/**: # use wildcards to match all namespaces
  teleop_twist_joy_node:
    ros__parameters:
      axis_linear:
        x: 1      # m/s
      scale_linear:
        x: 0.4    # m/s
      scale_linear_turbo:
        x: 1.0    # m/s
      axis_angular:
        yaw: 0    # rad/s
      scale_angular:
        yaw: 1.8  # rad/s
      scale_angular_turbo:
        yaw: 2.4  # rad/s
      enable_button: 9
      enable_turbo_button: 5

  joy_node:
    ros__parameters:
      rate: 10.0
      deadzone: 0.1
      autorepeat_rate: 20.0
      dev: /dev/input/js0